name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  build-and-push-docker:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build . -t erisahalipaj2107/user-auth:latest
          docker push erisahalipaj2107/user-auth:latest

  restart-application:
    needs: build-and-push-docker
    runs-on: ubuntu-latest

    steps:
      - name: Restart Application
        run: |
          # Add your deployment logic here, e.g., using SSH to restart the server
          ssh -i ${{ secrets.SSH_KEY }} user@${{ secrets.DROPLET_IP }} "docker-compose -f /path/to/docker-compose.yml up -d"
